Project_Group3/Controllers/VoucherController.cs
using System;
using System.Collections.Generic;
using System.Diagnostics;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.Extensions.Logging;
using Project_Group3.Models;
using WebLibrary.DAO;
using WebLibrary.Models;
using WebLibrary.Repository;

namespace Project_Group3.Controllers
{
    public class VoucherController : Controller
    {
        IVoucherRepository voucherRepository = null;

        public VoucherController()
        {
            voucherRepository = new VoucherRepository();
        }

        public IActionResult Index()
        {
            try
            {
                var list = voucherRepository.VouchersList();
                return View(list);
            }
            catch (System.Exception)
            {
                return View();
            }
        }

        public IActionResult Create() => View();

        [HttpPost]
        public IActionResult Create(Voucher voucher)
        {
            try
            {
                if (voucher == null)
                {
                    ViewBag.err = "voucher cannot be null. Please try again.";
                    return View();
                }

                if (ModelState.IsValid)
                {
                    var generatedCode = voucherRepository.GenerateRandomCode();
                    voucher = new Voucher
                    {
                        CodeVoucher = generatedCode,
                        AdminId = 1,
                        PercentDiscount = voucher.PercentDiscount,
                        EndAt = voucher.EndAt,
                        StartAt = voucher.StartAt,
                        IsActive = voucher.IsActive
                    };
                    string voucherInfo = $"Voucher ID: {voucher.VoucherId}\n" +
                                         $"Code Voucher: {voucher.CodeVoucher}\n" +
                                         $"Admin ID: {voucher.AdminId}\n" +
                                         $"Percent Discount: {voucher.PercentDiscount}\n" +
                                         $"End Date: {voucher.EndAt}\n" +
                                         $"Start Date: {voucher.StartAt}\n" +
                                         $"Is Active: {voucher.IsActive}";
                    Console.WriteLine(voucherInfo);
                    voucherRepository.CreateVoucher(voucher);
                    return RedirectToAction("Index");
                }
                else
                {
                    var errorProperties = ModelState.Keys.Where(k => ModelState[k].Errors.Any()).ToList();
                    ViewBag.ErrorProperties = errorProperties;
                    return View(voucher);
                }
            }
            catch (Exception ex)
            {
                ViewBag.Message = ex.Message;
                return View(voucher);
            }
        }

        public IActionResult Delete(int? id)
        {
            try
            {
                if (id == null) return NotFound();

                var voucher = voucherRepository.GetVoucherByID(id.Value);

                if (voucher == null)
                {
                    return NotFound();
                }

                return View(voucher);
            }
            catch (System.Exception)
            {
                return View();
            }
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult DeleteConfirmed(int id)
        {
            try
            {
                voucherRepository.Remove(id);
                TempData["DeleteSuccess"] = true;
                return RedirectToAction(nameof(Index));
            }
            catch (Exception ex)
            {
                ViewBag.Message = ex.Message;
                return View();
            }
        }
    }
}

Project_Group3/Views/Voucher/Create.cshtml
@model WebLibrary.Models.Voucher
@{
    ViewData["Title"] = "Create Voucher";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<link rel="stylesheet" href="~/fonts/boxicons.css" />
<div class="card bg-theme p-0 mt-2 mb-5">
    <div class="container my-3">
        <form asp-action="Create">
            <input asp-for="AdminId" type="hidden" class="form-control">
            <div class="mb-3 text-theme">
                <label asp-for="PercentDiscount" class="form-label">Percentage Discount</label>
                <input asp-for="PercentDiscount" type="number" class="form-control">
                <span asp-validation-for="PercentDiscount" class="text-danger"></span>
            </div>
            <div class="mb-3 text-theme">
                <label asp-for="StartAt" class="form-label">Start Date</label>
                <input asp-for="StartAt" type="datetime-local" class="form-control">
                <span asp-validation-for="StartAt" class="text-danger"></span>
            </div>
            <div class="mb-3 text-theme">
                <label asp-for="EndAt" class="form-label">End Date</label>
                <input asp-for="EndAt" type="datetime-local" class="form-control">
                <span asp-validation-for="EndAt" class="text-danger"></span>
            </div>
            <div class="mb-3 text-theme form-check" style="width: 20%; margin-left: -1rem;">
                <label asp-for="IsActive" class="form-check-label font-weight-bold mr-4">Active</label>
                <select asp-for="IsActive" class="form-control">
                    <option value="">-- Select --</option>
                    <option value="true">Yes</option>
                    <option value="false">No</option>
                </select>
                <span asp-validation-for="IsActive" class="text-danger"></span>
            </div>

            <p class="text-danger">@ViewBag.err</p>
            <button type="submit" class="btn btn-success">Create</button>
            <a asp-action="Index" class="btn btn-secondary">Cancel</a>
        </form>
    </div>
</div>

@{
    var errorMessage = ViewBag.Message as string;
}

@if (!string.IsNullOrEmpty(errorMessage))
{
    <div class="alert alert-danger">@errorMessage</div>
}

Project_Group3/Views/Voucher/Delete.cshtml
@model WebLibrary.Models.Voucher
@{
    ViewData["Title"] = "Delete Voucher";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<link rel="stylesheet" href="~/fonts/boxicons.css" />
<div class="card bg-theme p-0 mt-2 mb-5">
    <div class="container my-3">
        <form asp-action="DeleteConfirmed" class="ml-5 mt-3 mb-3">
            <input asp-for="VoucherId" type="hidden" class="form-control">
            <div class="mb-3 text-theme">
                <label asp-for="PercentDiscount" class="form-label">Percentage Discount</label>
                <input asp-for="PercentDiscount" type="number" class="form-control" readonly>
                <span asp-validation-for="PercentDiscount" class="text-danger"></span>
            </div>
            <div class="mb-3 text-theme">
                <label asp-for="StartAt" class="form-label">Start Date</label>
                <input asp-for="StartAt" type="datetime-local" class="form-control" readonly>
                <span asp-validation-for="StartAt" class="text-danger"></span>
            </div>
            <div class="mb-3 text-theme">
                <label asp-for="EndAt" class="form-label">End Date</label>
                <input asp-for="EndAt" type="datetime-local" class="form-control" readonly>
                <span asp-validation-for="EndAt" class="text-danger"></span>
            </div>
            <div class="mb-3 text-theme form-check" style="width: 20%; margin-left: -1rem;">
                <label asp-for="IsActive" class="form-check-label font-weight-bold mr-4">Active</label>
                <input type="text" class="form-control" asp-for="IsActive"readonly>
                <span asp-validation-for="IsActive" class="text-danger"></span>
            </div>

            <p class="text-danger">@ViewBag.err</p>
            <button type="submit" class="btn btn-danger">Delete</button>
            <a asp-action="Index" class="btn btn-secondary">Cancel</a>
        </form>
    </div>
</div>

@if (!string.IsNullOrEmpty(ViewBag.Message))
{
    <div class="alert alert-danger">@ViewBag.Message</div>
}

Project_Group3/Views/Voucher/Index.cshtml
@model List<WebLibrary.Models.Voucher>
@{
    ViewData["Title"] = "Index";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<link rel="stylesheet" href="~/fonts/boxicons.css" />

@if (TempData["EditSuccess"] != null)
{
    <div id="editAlert"
        class="alert alert-@((bool)TempData["EditSuccess"] ? "success" : "danger") alert-dismissible fade show">
        @((bool)TempData["EditSuccess"] ? "Instructor edited successfully." : "Failed to edit instructor.")
        <div id="progressBar"></div>
    </div>
}

@if (TempData["DeleteSuccess"] != null)
{
    <div id="deleteAlert"
        class="alert alert-@((bool)TempData["DeleteSuccess"] ? "success" : "danger") alert-dismissible fade show">
        @((bool)TempData["DeleteSuccess"] ? "Instructor deleted successfully." : "Failed to delete instructor.")
        <div id="progressBar"></div>
    </div>
}
<div class="card bg-theme p-0 mt-2 mb-5">
    <div class="container my-3">
        <a class="btn btn-success my-2" asp-action="Create">Create</a>
        <table class="table">
            <thead>
                <tr>
                    <th>Code Voucher</th>
                    <th>Percent Discount</th>
                    <th>Start At</th>
                    <th>End At</th>
                    <th>Is Active</th>
                    <th></th>
                </tr>
            </thead>
            <tbody>
            @foreach (var item in Model)
            {
                <tr>
                    <td>@item.CodeVoucher</td>
                    <td>@item.PercentDiscount</td>
                    <td>@item.StartAt</td>
                    <td>@item.EndAt</td>
                    <td>@item.IsActive</td>
                    <td><a href="@Url.Action("Delete", "Voucher", new{id = @item.VoucherId})" class="btn btn-danger">Delete</a></td>
                </tr>
            }
            </tbody>
        </table>
    </div>
</div>